// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmxgzepryoyqshxtjody.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhteGd6ZXByeW95cXNoeHRqb2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMjMzNDAsImV4cCI6MjA1ODU5OTM0MH0.ydMnI8VSPnCMM4ROOWIYg0MS6PvAQ9Man993GtBUmC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);